### ISSUE TITLE
If rebinding is not planned, F is a bad choice for the freecam key

### ISSUE THREAD

**Issue by glyphical** [giosuel/imperium#1]
This is a fantastic mod, but I would highly recommend switching the freecam key to one further away from and less likely to be utilized in the typical WASD setup. I am currently unable to use Imperium as my A key is broken and I need to use ESDF to maneuver--which, as you could imagine, introduces some issues. :P

**Comment by giosuel** [comment]
Thanks for the report! I plan on making the freecam's WASD inputs dependent on the game's WASD bindings which will hopefully solve this issue.

**Comment by glyphical** [comment]
My issue is less the way freecam controls and more the way Freecam is started--right now, initiating freecam is done with the button that is, for me, Strafe Right. I would recommend moving it further out to G or something of the sort!

**Comment by NeatWolf** [comment]
I'm also facing several key conflicts and can't use the tool at all until all its key are remappable in their own category (such as what ReservedItemSlotCore does with each slot).
I can see a lot of effort put into the plugin but still has some issues with mods and v50

**Comment by MLIOSBond** [comment]
@glyphical @NeatWolf if you're curios, I found a solution that I described in #16 (link to the [comment][1])


[1]: https://github.com/giosuel/imperium/issues/16#issuecomment-2094280550

**Comment by NeatWolf** [comment]
> @glyphical @NeatWolf if you're curious, I found a solution that I described in #16 (link to the [comment](https://github.com/giosuel/imperium/issues/16#issuecomment-2094280550))

Hex editing? Yes, it's a solution but I feel that implementing a custom rebindable key in the config would be the smoothest solution for all imperium users :)

**Comment by giosuel** [comment]
I added support for InputUtils in v0.2.0 (8b53880098f6abcb4ae4df9e2838a9b2bbc634d8).
