### ISSUE TITLE
[Feature Request] Prevent ship leaving upon death without godmode

### ISSUE THREAD

**Issue by nmarsh12** [giosuel/imperium#10]
Any way there could be a toggle to make the ship stay when all players die, regardless of whether players are in godmode? I'd like to be able to revive myself while still being able to die when spawning and fighting enemies. There's a chance this is a feature already and I'm just blind

**Comment by giosuel** [comment]
An option to disable the ship leaving early was added in 6c05af8be0a80abfea030aff7f5d0a0b597ffb32.
