### ISSUE TITLE
[Feature Request] Willa therey be keybind rebindin / compatibiliti withs LethalCompany_InputUtils

### ISSUE THREAD

**Issue by Flloppis** [giosuel/imperium#13]
Ah havva friend who lovesii thissa mod, theyya host aswell. 
However- theyya use other keys for otherra mods and some offa 'em conflict!!
Willa there be rebindable menu inna one offa tha F1,F2,F3,F4,F5,F6 Keysi?

Oo- anda generalimprovements doesnt letta me openn upp menus with F1-F6 keys!
Thankii yer so muchii!! :>

**Comment by giosuel** [comment]
Yes, I am planning on supporting InputUtils in the future.

**Comment by giosuel** [comment]
Addec InputUtils compatibility in 8b53880098f6abcb4ae4df9e2838a9b2bbc634d8.
