### ISSUE TITLE
Reviving a player doesn't work as expected (networking issue)

### ISSUE THREAD

**Issue by LouisSilva** [giosuel/imperium#17]
When the server/host player revives another player, the server and client players see different things.

The server/host player sees the revived player standing still infront of the ship doors: ![server](https://github.com/giosuel/imperium/assets/37211367/4203be9a-29f8-4f83-99e5-14efa01e04b1)

The client player who was revived is still just in spectator mode, and does not see their body standing infront of the ship doors: ![client](https://github.com/giosuel/imperium/assets/37211367/2c14c472-3ac4-4057-a813-6ddf700da6c8)

**Comment by giosuel** [comment]
This was fixed in 6c05af8be0a80abfea030aff7f5d0a0b597ffb32.
