### ISSUE TITLE
Imperium as a customization tool

### ISSUE THREAD

**Issue by 588-th** [giosuel/imperium#2]
On the mod page, you have indicated that imperium is positioned as a debugging tool. But can it or will it also be positioned as a tool for customizing the game, like other mods such as "GeneralImprovements", "LethalUtilities", and "AdvancedCompany", among others?

Imperium has already helped me by removing some mods, such as "RemoveCameraFilter", "KillBind" and "DanceTools", at this stage. I would like Imperium to continue allowing me to reduce the number of mods in my build and avoid potential incompatibilities. Ideally, imperium could replace larger mods like GeneralImprovements.

Imperium already has a wide range of features and I see this mod as a large single game control center in the future.

**Comment by giosuel** [comment]
Imperium is not really meant for regular gameplay. It is intended to be an all-in-one tool for debugging and testing, meaning I generally do not plan to implement gameplay altering features from mods like GeneralImprovements.

If you have any suggestions for debugging features that could be added to reduce the debug-mod list even more, feel free to open an issue and I'll take a look!
