### ISSUE TITLE
[BUG] Infinite Stamina Always

### ISSUE THREAD

**Issue by MPRATCH-V2** [giosuel/imperium#23]
I have infinite stamina always while using this mod even when the mod option is not enabled. I have an extensive modpack which very well may be causing a conflict somewhere. I also bugged a save and made it so that no enemies spawn anymore not sure how but resetting the imperium config fixed the issue. Clients were also still able to use the menu even with the option disabled. I may revisit this issue another day when I have time to test which if any mods conflict. This is by far the best dev menu/debug tool I've ever used and it's understandable if there area few issues with it as it's in public beta. Dev please don't abandon this tool anytime soon.

My modpack minus imperium: 018fc324-29ba-c991-4e01-3767cdc3d102

p.s. dev plz allow keybind rebinding F is my flashlight button

Edit 1: Removing General Improvements fixed the infinite stamina not sure why. I'm still having plenty of issues with my pack atm as I just got back into LC and removing General Improvements forced me to redo a lot of my pack. I will keep try to update this post anytime I come across something potentially incompatible with Imperium

Edit 2: I've decided to scrap my entire modpack and rebuild from the ground up. Imperium works perfectly on its own so it must have been an incompatibility somewhere. I intend on leaving this issue open so I can document for others mods I encounter that conflict with Imperium. Dev if you are not okay with me doing this here feel free to close this issue.

**Comment by Zeralit** [comment]
FYI General Improvement automatically enables infinite stamina when dev tools are enabled. 
From the changelog:

> - Added infinite sprint if debug tools and invincibility are enabled (mostly so I can test more easily with [LethalDevMode]).
https://thunderstore.io/c/lethal-company/p/ShaosilGaming/GeneralImprovements/changelog/

**Comment by MPRATCH-V2** [comment]
> FYI General Improvement automatically enables infinite stamina when dev tools are enabled. From the changelog:

I was unaware of this thanks for the info! I'm not sure why but this mod seems to have activated for me without enabling godmode. Additionally the vent timers were visible even with the box unchecked so I assume I must have had another conflict somewhere.

**Comment by MPRATCH-V2** [comment]
As I have now rebuilt my modpack I will no longer be documenting the conflicts from the previous one. Closing this issue.
