### ISSUE TITLE
tutor

### ISSUE THREAD

**Issue by AK1k1** [giosuel/imperium#3]
if there is tutorial?
not into this stuff but wanna test a lot things with this debug menu

also tried to simply put this in "plugin" folder but nothing happens to work

**Comment by giosuel** [comment]
There is currently no tutorial besides the README. To install the mod, either extract the ZIP into the `BepInEx/plugins` folder or use a mod manager like [r2modman](https://thunderstore.io/package/ebkr/r2modman/) that installs it for you.

**Comment by AK1k1** [comment]
> There is currently no tutorial besides the README. To install the mod, either extract the ZIP into the `BepInEx/plugins` folder or use a mod manager like [r2modman](https://thunderstore.io/package/ebkr/r2modman/) that installs it for you.

thank you
