### ISSUE TITLE
[Feature Request] Route menu resize for custom moons

### ISSUE THREAD

**Issue by LimerBoy** [giosuel/imperium#32]
![image](https://github.com/giosuel/imperium/assets/43149460/33d823fb-12c8-4feb-86ca-3ca2310e47a2)

The list of moons does not fit on the screen, can you fix this?

**Comment by giosuel** [comment]
Haha, when I implemented this UI, I did not intend for this many custom moons to be added. I will look into this.

**Comment by giosuel** [comment]
Fixed in 8b53880098f6abcb4ae4df9e2838a9b2bbc634d8.
