### ISSUE TITLE
Unable to open any F-key menus

### ISSUE THREAD

**Issue by jacket430** [giosuel/imperium#4]
Hey there,

I'm currently working on a modpack and found out about this tool in a YouTube video, thought it would be perfect for testing things. Unfortunately, I'm only able to get the free cam to work, which isn't really what I wanted this for. I'm honestly completely unsure what could be causing this issue, as nothing seems to be appearing in the logs when pressing the keys or anything. 

I do not have any keybinds set to the F keys in the InputUtils rebind screen.

Here is the list of mods I'm using at the moment, if you have any idea which one could be causing this issue (if any) please let me know, as I'd love to use this tool. But as it currently stands I can't seem to access most of the features without the F keys working. (note, they do work outside of LC, they just don't seem to do anything with the mod installed.)

Running Windows 11 Pro on the latest version of LC (v50)

1. BepInEx-BepInExPack-5.4.2100
2. loaforc-loaforcsSoundAPI-1.0.10
3. Evaisa-FixPluginTypesSerialization-1.1.1
4. Evaisa-HookGenPatcher-0.0.5
5. Hardy-LCMaxSoundsFix-1.1.0
6. Sigurd-CSync-4.1.0
7. NotAtomicBomb-TerminalApi-1.5.2
8. Evaisa-LethalLib-0.15.1
9. BMX-LobbyCompatibility-1.1.0
10. AinaVT-LethalConfig-1.4.0
11. ShaosilGaming-GeneralImprovements-1.1.12
12. FlipMods-ReservedItemSlotCore-2.0.18
13. FlipMods-ReservedFlashlightSlot-2.0.3
14. notnotnotswipez-MoreCompany-1.8.1
15. Zaggy1024-OpenBodyCams-1.3.0
16. FlipMods-ReservedWalkieSlot-2.0.4
17. LethalResonance-LETHALRESONANCE-4.2.3
18. loaforc-FacilityMeltdownExperimental-2.5.7
19. EliteMasterEric-Coroner-1.6.2
20. Pooble-LCBetterSaves-1.7.3
21. Blorb-WeatherMultipliers-1.1.0
22. Hexnet111-SuitSaver-1.1.4
23. MegaPiggy-BuyableShotgun-1.1.0
24. MegaPiggy-BuyableShotgunShells-1.1.0
25. x753-More_Suits-1.4.3
26. Verity-TooManySuits-1.0.8
27. Bobbie-UniTask-2.5.0
28. Bobbie-NAudio-2.2.2
29. qwbarch-BarchLib-1.0.0
30. qwbarch-Mirage-1.3.2
31. darmuh-darmuhsTerminalStuff-3.0.4
32. sunnobunno-YippeeMod-1.2.4
33. Darkbrewery-Emblem-1.2.5
34. Atomicz_A-ScrollReverser-1.0.1
35. TwinDimensionalProductions-CoilHeadStare-1.0.9
36. mrgrm7-LethalCasino-0.5.1
37. Rune580-LethalCompany_InputUtils-0.7.3
38. Electric131-OuijaBoard-1.5.3
39. quackandcheese-ToggleMute-1.3.1
40. Evaisa-LethalThings-0.10.2
41. CHILLAX-ChillaxSCRAPS-0.6.0
42. FutureSavior-Hold_Scan_Button-1.1.1
43. EladNLG-EladsHUD-1.2.1
44. Jordo-NeedyCats-1.2.1
45. Midge-PushCompany-1.2.0
46. FlipMods-TooManyEmotes-2.1.2
47. KoderTeh-Boombox_Controller-1.2.4
48. TeamClark-Vault_Boy_Suit-1.0.0
49. Kittenji-Dont_Touch_Me-1.2.1
50. Entity378-SellBodiesFixed-1.7.1
51. Jacket430-430 Resources-1.0.0 (Pack resources, only contains outfits/skins at the moment)
52. ironbean-Remove_Level_Badge-1.0.0
53. fumiko-CullFactory-1.0.3
54. anormaltwig-LateCompany-1.0.13
55. malco-Lategame_Upgrades-3.5.5
56. taffyko-BetterSprayPaint-2.0.2
57. femboytv-LethalPosters-1.2.0

**Comment by Xenorvya** [comment]
Having the same issue here. Pressing X and F works, but the f keys don't work at all. Using an HP Windows 10 laptop.

**Comment by TechTonic02** [comment]
Lethal lib seems to be causing the problem as far as I know

**Comment by Xenorvya** [comment]
For me it was the "Dont_Touch_Me" entity. The menu now opens, but enemies are invincible and time goes by fast (when I have a mod to slow it down called Longer_Day) so I suppose I won't be using imperium with mods.

**Comment by jacket430** [comment]
I can confirm that after updating Dont_Touch_Me to v1.2.2 the problem persists. 

Also, disabling Dont_Touch_Me altogether still seems to cause the issue to happen with Lethal Lib installed.

**Comment by NeatWolf** [comment]
Hi, just adding my +1 to this issue - I'd like to say "I won't use it with mods" but, I feel that would be a huge limitation.
The tool seems amazing from the pics - it's a shame I'm still unable to try it on official v50.

I'll try to uninstall  Don't touch me. I wonder if it's that mod that's causing LethalCompanyVariables v2.2.0 from properly setting spawn rates for other entities. The weather-dependant plugin mentioned above indeed overrides most of the overlapping settings.

**Comment by FabrizioRomanoff** [comment]
For me, it was "LethalCompany_InputUtils" that was causing the F-key menus to not work. Disabling that mod and only that mod solved the issue for me. But that still isn't ideal since a good amount of mods I use and really enjoy require that mod to be active (Lategame_Upgrades, TeleportDecline, BetterSprayPaint)

**Comment by jacket430** [comment]
Yeah that's where I'm at, I use quite a few of those mods so it's kind of a non starter.

**Comment by giosuel** [comment]
It is currently not intended that Imperium works with any arbitrary mods. It's not trivial to just support any mods (especially large, content-modifying mods), as every mod does something else and I need to look at every mod individually.

**Comment by FabrizioRomanoff** [comment]
Makes sense. Imperium is still in beta, afterall. And I mean, I don't think Imperium was ever intended to be used for your regular, casual play, it's for debugging and such. I just play with over 200 mods so bugs, glitches and other issues happen a lot so it's nice to have debugging options for that. And Imperium is the best and most extensive debugging mod I've seen so far so let's be patient to see how things turn out.

**Comment by giosuel** [comment]
> Hey there,
> 
> I'm currently working on a modpack and found out about this tool in a YouTube video, thought it would be perfect for testing things. Unfortunately, I'm only able to get the free cam to work, which isn't really what I wanted this for. I'm honestly completely unsure what could be causing this issue, as nothing seems to be appearing in the logs when pressing the keys or anything.
> 
> I do not have any keybinds set to the F keys in the InputUtils rebind screen.
> 
> Here is the list of mods I'm using at the moment, if you have any idea which one could be causing this issue (if any) please let me know, as I'd love to use this tool. But as it currently stands I can't seem to access most of the features without the F keys working. (note, they do work outside of LC, they just don't seem to do anything with the mod installed.)
> 
> Running Windows 11 Pro on the latest version of LC (v50)
> 
>     1. BepInEx-BepInExPack-5.4.2100
> 
>     2. loaforc-loaforcsSoundAPI-1.0.10
> 
>     3. Evaisa-FixPluginTypesSerialization-1.1.1
> 
>     4. Evaisa-HookGenPatcher-0.0.5
> 
>     5. Hardy-LCMaxSoundsFix-1.1.0
> 
>     6. Sigurd-CSync-4.1.0
> 
>     7. NotAtomicBomb-TerminalApi-1.5.2
> 
>     8. Evaisa-LethalLib-0.15.1
> 
>     9. BMX-LobbyCompatibility-1.1.0
> 
>     10. AinaVT-LethalConfig-1.4.0
> 
>     11. ShaosilGaming-GeneralImprovements-1.1.12
> 
>     12. FlipMods-ReservedItemSlotCore-2.0.18
> 
>     13. FlipMods-ReservedFlashlightSlot-2.0.3
> 
>     14. notnotnotswipez-MoreCompany-1.8.1
> 
>     15. Zaggy1024-OpenBodyCams-1.3.0
> 
>     16. FlipMods-ReservedWalkieSlot-2.0.4
> 
>     17. LethalResonance-LETHALRESONANCE-4.2.3
> 
>     18. loaforc-FacilityMeltdownExperimental-2.5.7
> 
>     19. EliteMasterEric-Coroner-1.6.2
> 
>     20. Pooble-LCBetterSaves-1.7.3
> 
>     21. Blorb-WeatherMultipliers-1.1.0
> 
>     22. Hexnet111-SuitSaver-1.1.4
> 
>     23. MegaPiggy-BuyableShotgun-1.1.0
> 
>     24. MegaPiggy-BuyableShotgunShells-1.1.0
> 
>     25. x753-More_Suits-1.4.3
> 
>     26. Verity-TooManySuits-1.0.8
> 
>     27. Bobbie-UniTask-2.5.0
> 
>     28. Bobbie-NAudio-2.2.2
> 
>     29. qwbarch-BarchLib-1.0.0
> 
>     30. qwbarch-Mirage-1.3.2
> 
>     31. darmuh-darmuhsTerminalStuff-3.0.4
> 
>     32. sunnobunno-YippeeMod-1.2.4
> 
>     33. Darkbrewery-Emblem-1.2.5
> 
>     34. Atomicz_A-ScrollReverser-1.0.1
> 
>     35. TwinDimensionalProductions-CoilHeadStare-1.0.9
> 
>     36. mrgrm7-LethalCasino-0.5.1
> 
>     37. Rune580-LethalCompany_InputUtils-0.7.3
> 
>     38. Electric131-OuijaBoard-1.5.3
> 
>     39. quackandcheese-ToggleMute-1.3.1
> 
>     40. Evaisa-LethalThings-0.10.2
> 
>     41. CHILLAX-ChillaxSCRAPS-0.6.0
> 
>     42. FutureSavior-Hold_Scan_Button-1.1.1
> 
>     43. EladNLG-EladsHUD-1.2.1
> 
>     44. Jordo-NeedyCats-1.2.1
> 
>     45. Midge-PushCompany-1.2.0
> 
>     46. FlipMods-TooManyEmotes-2.1.2
> 
>     47. KoderTeh-Boombox_Controller-1.2.4
> 
>     48. TeamClark-Vault_Boy_Suit-1.0.0
> 
>     49. Kittenji-Dont_Touch_Me-1.2.1
> 
>     50. Entity378-SellBodiesFixed-1.7.1
> 
>     51. Jacket430-430 Resources-1.0.0 (Pack resources, only contains outfits/skins at the moment)
> 
>     52. ironbean-Remove_Level_Badge-1.0.0
> 
>     53. fumiko-CullFactory-1.0.3
> 
>     54. anormaltwig-LateCompany-1.0.13
> 
>     55. malco-Lategame_Upgrades-3.5.5
> 
>     56. taffyko-BetterSprayPaint-2.0.2
> 
>     57. femboytv-LethalPosters-1.2.0

Do you have a thunderstore of this pack code by any chance? I am currently testing Imperium with other mods and I want to try to find the mod that is causing this problem as I have seen it before with another mod.

**Comment by jacket430** [comment]
Sure, here's the code for the TS/R2 profile: `018ef337-481f-676a-32c3-04b7e63940c0`

I'm working on a pack for some friends so I am using a personal git to track changes and make it easier to revert anything I mess up, [here is the link to the git as well](https://gitgud.io/jacket430/430-company-modpack) if there are any changes between the two.

**Comment by giosuel** [comment]
Thanks! I tried to use Imperium with your modpack and everything worked as expected. I have published some changes yesterday that should help with mod compatibility. Could you check if it works with the new version?

**Comment by jacket430** [comment]
Hey there,

I just gave it a shot with the newest updates and the menus are opening totally fine now. I'm blown away by the level of functionality this tool has, never seen anything like it in another game before. Amazing work! 

Thank you so much!
