### ISSUE TITLE
Imperium Failed to Acquire Access

### ISSUE THREAD

**Issue by dcomeau** [giosuel/imperium#40]
Updated to the new v0.2.0, when loading a save I get the usual "Imperium Access Granted" pop-up but then it switches to a failed to acquire access. Not sure if there's a mod incompatibility? Thunderstore Profile Code also included.

Profile code: 01907588-e448-557a-c137-edde85eef849
[LogOutput.log](https://github.com/user-attachments/files/16074802/LogOutput.log)

**Comment by KenIsStupid** [comment]
What did you do to fix this issue?

**Comment by inconspicuouscat** [comment]
> What did you do to fix this issue?

Likely to do with the version you're running. I had the exact same issue when running the release version (v50).
But when I loaded the beta, v55, it worked perfectly with my modpack (120 mods)

Right click Lethal Company > Properties > Betas > Beta Participation > Public_Beta
And then try again. This was my solution at least. If it doesn't work, try opening a ticket for the dev and describe your experience with the problem.

**Comment by dcomeau** [comment]
> What did you do to fix this issue?

Sorry I apparently didn't click comment when I closed this!

Like inconspicuouscat said, it was the version. I realized I'd missed the line on the changelog that this release was for v55, and it didn't say anywhere that it was compatible with v50. Jumped to the v55 beta and it worked fine!

**Comment by randomname267** [comment]
> > What did you do to fix this issue?
> 
> Likely to do with the version of Lethal Company that you're running. I had the exact same issue when running the release version (v50). But when I loaded the beta, v55, it worked perfectly with my modpack (120 mods)
> 
> Right click Lethal Company > Properties > Betas > Beta Participation > Public_Beta And then try again. This was my solution at least. If it doesn't work, try opening a ticket for the dev and describe your experience with the problem.

I switched to beta and it granted me access, but now once i start the ship it spawns the ship on the map and just doesnt let me leave, even when i overwrite doors it teleports me back like im in orbit? time doesnt start either and oracle doesnt work
