### ISSUE TITLE
Can't find a way to disable Ai movement like shown in video I've found this mod from

### ISSUE THREAD

**Issue by TGG12464** [giosuel/imperium#45]
Can't find a way to disable Ai movement like shown in video I've found this mod from. MasterClass video.
Or would this be a whole other mod that Imperium does not expert in?
Also for making the unused 3 players show up? How do people do that?

**Comment by giosuel** [comment]
You can pause entity AI by unchecking their checkboxes in the object explorer. Since the default 4 players are always present, you can freely teleport them around via the object explorer, just like any active player.
