### ISSUE TITLE
 mod conficts in v50 (imperium v0.1.9)

### ISSUE THREAD

**Issue by XBOXLIVE360a** [giosuel/imperium#48]
when i launch the game with the "DontTouchMe" mod imperium menus dont open and i get this error in the console

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Imperium.MonoBehaviours.ImpUI.MapUI.MinimapOverlay.Update () (at <2ed6dc40b2e64a40bf330371703d0436>:IL_0219)

![Screenshot 2024-08-14 020554](https://github.com/user-attachments/assets/db490f29-2467-4782-8890-8bf60086f21b)

**Comment by giosuel** [comment]
This issue has been fixed in https://github.com/giosuel/imperium/releases/tag/v0.2.2.
