### ISSUE TITLE
[Bug] "Instant Landing" Doesn't Actually Make the Ship Land Instantly

### ISSUE THREAD

**Issue by theluigiduck** [giosuel/imperium#59]
It just makes the doors opening, first spawn cycle, and clock showing up happen immediately. But the ship still has to slowly descend to the planet.

**Mod list:**
Imperium (obviously)
CullFactory
HotbarPlus
SellMyScrap
FixPluginTypesSerialization
PathfindingLagFix
FlashlightToggle
ShipLoot
HealthMetrics
DissonanceLagFix
LethalCompany_InputUtils
LethalNetworkAPI
OdinSerializer
BepInExPack

**Comment by YoshiRulz** [comment]
CNR with 0.2.7. I can provide pack code if desired.

**Comment by theluigiduck** [comment]
Suddenly fixed. No mod changes or anything. Not sure what the deal is but I guess it's fine now.
