### ISSUE TITLE
"69% sale" switch does not exist

### ISSUE THREAD

**Issue by theluigiduck** [giosuel/imperium#79]
This most recent version mentions the addition of a switch that toggles the 69% off sale easter egg, but I cannot find it anywhere. It either doesn't exist or is in some strange place that's incredibly difficult to find.

**Mod list:**
Imperium (ofc)
CruiserAdditions
CullFactory
TwoHandedMod
PredictableEggs
HootGenPatcher
CSync
CessilCellsCeaChells
UseItemsWhileOnShip
SellMyScrap
IntroTweaks
LCBetterSaves
FasterItemDropship
CruiserImproved
Crosshair
LethalNetworkAPI
HotbarPlus
FixPluginTypesSerialization
PathfidingLagFix
FlashlightToggle
ShipLoot
HealthMetrics
DissonanceLagFix
LethalCompany_InputUtils
OdinSerializer
BepInExPack

**Comment by theluigiduck** [comment]
Update: I found it, it's in the mod config, but it should really be in the in-game control panel or something.

**Comment by giosuel** [comment]
This was originally an easter-egg since I thought it wouldn't really be a big issue during debugging. I added the option to the config as I thought it wouldn't be important enough for the main UI .
