### ISSUE TITLE
Adding Custom Entities will prevent Menu's from opening

### ISSUE THREAD

**Issue by boogaeye** [giosuel/imperium#9]
No Errors are given as an output. I did some testing and the moment I add a new custom enemy from the thunderstore imperium stops allowing the menus from popping up. The freecam and minicam windows still work as intended though. Just none of the F1-F6 menus, teleport indicator or the employee hud.
(Though makes sense if you do not plan to support custom enemies)

**Comment by NeatWolf** [comment]
just popping in to say that the screenshots contain custom enemies, and native enemies have the "(native)" string appended. So maybe the issue is another or is custom-enemy specific?

**Comment by boogaeye** [comment]
> just popping in to say that the screenshots contain custom enemies, and native enemies have the "(native)" string appended. So maybe the issue is another or is custom-enemy specific?

Hmm interesting if thats so, maybe some entities using the LC_Example entity mod as a base template for making an entity is causing the issue. Ill dive in more to the root issue later when I have the time.

**Comment by giosuel** [comment]
Do you have a list of mods / thunderstore code, so I can test this? I have actually experienced this error myself with certain mods.

**Comment by boogaeye** [comment]
I will get back to you as soon as I can, as I have been busy.

**Comment by boogaeye** [comment]
Most menus now work withs the current build of Imperium except for the Spawn Cycle Menu which gives the error
```
LC_API.GameInterfaceAPI.Features.Player.ShowTip (System.String header, System.String message, System.Single duration, System.Boolean isWarning, System.Boolean useSave, System.String prefsKey) (at <9c282cdfc7dc4cca9fcc5df099e02800>:IL_0043)
LC_API.GameInterfaceAPI.Events.Patches.Internal.DisplayTipPatch.Prefix (System.String headerText, System.String bodyText, System.Boolean isWarning, System.Boolean useSave, System.String prefsKey) (at <9c282cdfc7dc4cca9fcc5df099e02800>:IL_0011)
(wrapper dynamic-method) HUDManager.DMD<HUDManager::DisplayTip>(HUDManager,string,string,bool,bool,string)
Imperium.Util.ImpOutput.Send (System.String text, System.String title, System.Boolean isWarning, Imperium.Util.NotificationType notificationType) (at <c42d373936674adea180e79f30d377da>:IL_004C)
Imperium.MonoBehaviours.ImpUI.OracleUI.OracleUI.CanOpen () (at <c42d373936674adea180e79f30d377da>:IL_000C)
Imperium.Core.ImpInterfaceManager.Open (System.Type type, System.Boolean toggleCursorState, System.Boolean closeOthers) (at <c42d373936674adea180e79f30d377da>:IL_0015)
Imperium.Core.ImpInterfaceManager.Open[T] (System.Boolean toggleCursorState, System.Boolean closeOthers) (at <c42d373936674adea180e79f30d377da>:IL_0000)
Imperium.Core.ImpInterfaceManager.Toggle[T] (System.Boolean toggleCursorState, System.Boolean closeOthers) (at <c42d373936674adea180e79f30d377da>:IL_0029)
Imperium.Core.ImpInterfaceManager.<Register>b__8_0[T] (UnityEngine.InputSystem.InputAction+CallbackContext _) (at <c42d373936674adea180e79f30d377da>:IL_0000)
UnityEngine.InputSystem.Utilities.DelegateHelpers.InvokeCallbacksSafe[TValue] (UnityEngine.InputSystem.Utilities.CallbackArray`1[System.Action`1[TValue]]& callbacks, TValue argument, System.String callbackName, System.Object context) (at <dbb0ce7b96144bd8bcbcb8b0d765f970>:IL_001B)
UnityEngine.InputSystem.LowLevel.<>c__DisplayClass7_0:<set_onUpdate>b__0(NativeInputUpdateType, NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate(NativeInputUpdateType, IntPtr)
```
I am fairly certain this is because of the [AnnounceMoonAndWeatherChange Mod](https://thunderstore.io/c/lethal-company/p/TestAccount666/AnnounceMoonAndWeatherChange/) which changes how hints are shown.

Opening a mod pack with Imperium + some other mods no longer produces the issue with hints.
